version: '3.8'

services:
  # Production frontend
  volview-insight-web:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:80"  # nginx serves on port 80
    environment:
      - NODE_ENV=production
    volumes:
      - ./volview-insight/src:/app/volview-insight/src
      - ./core:/app/core
    restart: unless-stopped

  # Production backend
  backend:
    environment:
      - PYTHON_ENV=production
    volumes:
      - ./volview-insight/server:/app
      - model-cache:/app/models
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Production orthanc
  orthanc:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Production hapi-fhir
  hapi-fhir:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Production orthanc-proxy
  orthanc-proxy:
    restart: unless-stopped