version: '3.8'

services:
  # Development frontend - Pure Vite dev server with hot reloading
  volview-insight-web:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.dev
    ports:
      - "8080:8080"  # Vite dev server (completely replaces base ports)
    environment:
      - NODE_ENV=development
      # Direct API calls to other services (browser → localhost)
      - VITE_REMOTE_SERVER_URL=http://localhost:4014/
      - VITE_DICOM_WEB_URL=http://localhost:5173/dicom-web/
      - VITE_FHIR_SERVER_URL=http://localhost:3000/hapi-fhir-jpaserver/fhir/
      # Local FHIR configuration for the LocalFHIR component
      - VITE_LOCAL_FHIR_SERVER_URL=http://localhost:3000/hapi-fhir-jpaserver/fhir
      - VITE_LOCAL_FHIR_SERVER_NAME=Local HAPI FHIR Server
      - VITE_PATIENT_IDENTIFIER=http://mimic.mit.edu/fhir/mimic/identifier/patient
    volumes:
      # Live code reloading
      - ./volview-insight/src:/app/volview-insight/src
      - ./core:/app/core
      # Prevent node_modules conflicts
      - /app/node_modules
      - /app/volview-insight/node_modules
      - /app/core/VolView/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]

  # Development backend with debug logging
  backend:
    environment:
      - PYTHON_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./volview-insight/server:/app
      - model-cache:/app/models
    command: ["python", "-m", "volview_server", "-P", "4014", "-H", "0.0.0.0", "--verbose", "volview_insight_methods.py"]

  # Development orthanc proxy
  orthanc-proxy:
    environment:
      - NODE_ENV=development
    volumes:
      - ./volview-insight/orthanc-proxy:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # Development orthanc
  orthanc:
    environment:
      - ORTHANC__AUTHENTICATION_ENABLED=false
      - ORTHANC__REMOTE_ACCESS_ALLOWED=true
      - ORTHANC__DICOM_WEB_ENABLED=true
      - ORTHANC__DICOM_WEB_ROOT=/dicom-web/
      - ORTHANC__STORAGE_DIRECTORY=/var/lib/orthanc/db
      - ORTHANC__DATABASE_DIRECTORY=/var/lib/orthanc/db
      - ORTHANC__INDEX_DIRECTORY=/var/lib/orthanc/db
      - ORTHANC__HTTP_PORT=8042
      - ORTHANC__DICOM_PORT=4242
    volumes:
      - orthanc-data:/var/lib/orthanc/db